---
- name: check ruby version
  command: /bin/bash -c -l 'eval "$(rbenv init -)" && rbenv versions'
  register: current_ruby
- name: install ruby
  command: rbenv install {{ ruby.version }}
  when: ruby.version not in current_ruby.stdout
  ignore_errors: true
- name: set ruby global
  command: rbenv global {{ ruby.version }}
  when: ruby.global == true
